[package]
name = "clocky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = {version = "4.5.10", features = ["derive"] }
rusqlite = "0.26.3"
